[package]
name = "guessing_game"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

gtk = "0.17.1"
pango = "0.17.0"
atk = "0.17.1"
gdk-pixbuf = "0.18.0"